version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - room-user-mysql

  room-user-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: guan7872
      MYSQL_DATABASE: roomData
    volumes:
      - room-user-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  room-user-mysql-data:

networks:
  micro-network:
    external: true