version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - room-admin-mysql

  room-admin-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: guan7872
      MYSQL_DATABASE: roomData
    volumes:
      - room-admin-mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  room-admin-mysql-data:

networks:
  micro-network:
    external: true
