services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      - hotel-user-mysql

  hotel-user-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: guan7872
      MYSQL_DATABASE: hotelData
    volumes:
      - hotel-user-mysql-data:/var/lib/mysql
    ports:
      - "3309:3306"

volumes:
  hotel-user-mysql-data:

networks:
  micro-network:
    external: true
